# It contains the default values for training a Conformer-CTC ASR model, large size (~120M) with CTC loss and sub-word encoding.

# Architecture and training config:
# Here are the recommended configs for different variants of Conformer-CTC, other parameters are the same as in this config file.
# One extra layer (compared to original paper) is added to the medium and large variants to compensate for replacing the LSTM decoder with a linear one.
#
#  +--------------+---------+---------+----------+------------------+------------+-----+
#  | Model        | d_model | n_heads | n_layers | conv_kernel_size | time_masks | lr  |
#  +==============+=========+========+===========+==================+============+=====+
#  | Small   (13M)|   176   |    4   |    16     |        31        |     5      | 5.0 |
#  +--------------+---------+--------+-----------+------------------+------------+-----+
#  | Medium  (30M)|   256   |    4   |    18     |        31        |     5      | 5.0 |
#  +--------------+---------+--------+-----------+------------------+------------+-----+
#  | Large  (121M)|   512   |    8   |    18     |        31        |     10     | 2.0 |
#  +------------------------+--------+-----------+------------------+------------+-----+
#  | XLarge (635M)|  1024   |    8   |    24     |         5        |     10     | 6.4 |
#  +--------------+---------+--------+-----------+------------------+------------+-----+
#
# Default learning parameters in this config are set for global batch size of 2K while you may use lower values.
# To increase the global batch size with limited number of GPUs, you may use higher accumulate_grad_batches.
# However accumulate_grad_batches is better to be avoided as long as the global batch size is large enough and training is stable.

# You may find more info about Conformer-CTC here: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/asr/models.html#conformer-ctc
# Pre-trained models of Conformer-CTC can be found here: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/asr/results.html
# The checkpoint of the large model trained on LibriSpeech with this recipe can be found here: https://ngc.nvidia.com/catalog/models/nvidia:nemo:stt_en_conformer_ctc_large_ls

# We suggest to use trainer.precision=bf16 for GPUs which support it otherwise trainer.precision=16 is recommended.
# Using bf16 or 16 would make it possible to double the batch size and speedup training/inference. If fp16 is not stable and model diverges after some epochs, you may use fp32.
# Here are the suggested batch size per GPU for each precision and memory sizes:
#  +-----------+------------+------------+
#  | Precision | GPU Memory | Batch Size |
#  +===========+============+============+
#  | 32        |    16GB    |     8      |
#  |           |    32GB    |     16     |
#  |           |    80GB    |     32     |
#  +-----------+------------+------------+
#  | 16 or     |    16GB    |     16     |
#  | bf16      |    32GB    |     32     |
#  |           |    80GB    |     64     |
#  +-----------+------------+------------+
# Note:  They are based on the assumption of max_duration of 20. If you have longer or shorter max_duration, then batch sizes may need to get updated accordingly.


name: "Conformer-CTC-BPE"

model:
  sample_rate: 16000
  log_prediction: true # enables logging sample predictions in the output during training
  ctc_reduction: 'mean_batch'
  skip_nan_grad: false
  char_labels: 
    update_labels: false

  train_ds:
    manifest_filepath: ???
    sample_rate: ${model.sample_rate}
    batch_size: 32  # You may increase batch_size if your memory allows
    shuffle: true
    num_workers: 16
    pin_memory: true
    use_start_end_token: false
    trim_silence: false
    max_duration: 30 # It is set for LibriSpeech, you may need to update it for your dataset
    min_duration: 0.1
    # Tarred datasets
    is_tarred: false
    tarred_audio_filepaths: null
    shuffle_n: 2048
    # Bucketing params
    bucketing_strategy: "synced_randomized"
    bucketing_batch_size: 8
    augmentor:
      prob: 0.5
      pipeline:
        - 
          - time_stretch:
              stretch_factor_range: [0.85, 1.15]
              stft_win_length: 320
              stft_hop_length: 160
              stft_nfft: 1024
        -
          - speed_perturbation:
              min_speed: 0.85
              max_speed: 1.15
        -
          - drop_sample_augment:
              frame_size: 800
              min_drop: 8
              max_drop: 40
        - 
          - gain:
              min_db: -30
              max_db: 0
              min_segments: 2
              max_segments: 4
              sample_rate: 16000
              fade: true
        -
          - low_shelf_filter:
              sample_rate: ${model.sample_rate}
              prob: 1.0
              min_center_frequency: 40.0
              max_center_frequency: 3000.0
              min_gain_db: -18
              max_gain_db: 18
              min_q: 0.1
              max_q: 0.99
        -
          - high_shelf_filter:
              sample_rate: ${model.sample_rate}
              prob: 1.0
              min_center_frequency: 300.0
              max_center_frequency: 4000.0
              min_gain_db: -18
              max_gain_db: 18
              min_q: 0.1
              max_q: 0.99
        -
          - aliasing:
              sample_rate: ${model.sample_rate}
              prob: 1.0
              min_sample_rate: 6000
              max_sample_rate: 8000
        -
          - add_gaussian_noise:
              prob: 1.0
              min_amplitude: 0.003
              max_amplitude: 0.02
              batch_agnostic: true
        -
          - reverb_echo:
              initial: 0.2
              prob: 1.0
              rt60: [1.1, 1.9]
              repeat: 3
              jitter: 0.5
              keep_clean: 0.1
              sample_rate: ${model.sample_rate}
        -
          - noise_augment:
              noise_dir: path/to/noise/dataset
        -
          - noise_augment:
              noise_dir: path/to/music/dataset
        - 
          - audio_mix:
              language_dir: path/to/other/language/audio/dir
              segments_dir: path/to/train/audio/vad/segments/dir
              max_audio_length: 30
              prob: 0.2
              num_other_audio_files: 3
        -
          - noise_augment:
              noise_dir: path/to/noise/dataset
          - reverb_echo:
              initial: 0.2
              prob: 1.0
              rt60: [1.1, 1.9]
              repeat: 3
              jitter: 0.5
              keep_clean: 0.1
              sample_rate: ${model.sample_rate}
          - gain:
              min_db: -30
              max_db: -5
              min_segments: 2
              max_segments: 4
              sample_rate: 16000
              fade: true
        -
          - speed_perturbation:
              min_speed: 0.85
              max_speed: 1.15
              is_batch_agnostic: true
          - drop_sample_augment:
              frame_size: 800
              min_drop: 8
              max_drop: 40
          - gain:
              min_db: -30
              max_db: -5
              min_segments: 2
              max_segments: 4
              sample_rate: 16000
              fade: true

  validation_ds:
    manifest_filepath: ["path/to/eval/dataset1", "path/to/eval/dataset2"]
    sample_rate: ${model.sample_rate}
    batch_size: 32 # You may increase batch_size if your memory allows
    max_duration: 30
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false

  test_ds:
    manifest_filepath: null
    sample_rate: ${model.sample_rate}
    batch_size: 4 # You may increase batch_size if your memory allows
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false

  # Recommend small vocab size of 128 or 256 when using 4x sub-sampling
  tokenizer: # Use for spe/bpe based tokenizer models
    update_tokenizer: True
    dir: path/to/tokenizer  # Path to directory which contains either tokenizer.model (bpe) or vocab.txt (for wpe)
    type: bpe  # Can be either bpe (SentencePiece tokenizer) or wpe (WordPiece tokenizer)

  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    sample_rate: ${model.sample_rate}
    normalize: "per_feature"
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    features: 80
    n_fft: 512
    log: true
    frame_splicing: 1
    dither: 0.00001
    pad_to: 0
    pad_value: 0.0

  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 2 # Set to zero to disable it
    # you may use lower time_masks for smaller models to have a faster convergence
    time_masks: 5 # Set to zero to disable it
    freq_width: 27
    time_width: 0.05

  encoder:
    _target_: nemo.collections.asr.modules.ConformerEncoder
    feat_in: ${model.preprocessor.features}
    feat_out: -1 # You may set it if you need different output size other than the default d_model
    n_layers: 17
    d_model: 512

    # Sub-sampling params
    subsampling: striding # vggnet or striding, vggnet may give better results but needs more memory
    subsampling_factor: 4 # Must be power of 2
    subsampling_conv_channels: -1 # -1 sets it to d_model

    # Feed forward module's params
    ff_expansion_factor: 4

    # Multi-headed Attention Module's params
    self_attention_model: rel_pos # rel_pos or abs_pos
    n_heads: 8 # May need to be lower for smaller d_models
    # [left, right] specifies the number of steps to be seen from left and right of each step in self-attention
    att_context_size: [-1, -1] # -1 means unlimited context
    xscaling: true # Scales up the input embeddings by sqrt(d_model)
    untie_biases: true # Unties the biases of the TransformerXL layers
    pos_emb_max_len: 5000

    # Convolution module's params
    conv_kernel_size: 31
    conv_norm_type: 'batch_norm' # batch_norm or layer_norm or groupnormN (N specifies the number of groups)
    # conv_context_size can be"causal" or a list of two integers while conv_context_size[0]+conv_context_size[1]+1==conv_kernel_size
    # null means [(kernel_size-1)//2, (kernel_size-1)//2], and 'causal' means [(kernel_size-1), 0]
    conv_context_size: null

    ### Regularization
    dropout: 0.1 # The dropout used in most of the Conformer Modules
    dropout_pre_encoder: 0.1 # The dropout used before the encoder
    dropout_emb: 0.0 # The dropout used for embeddings
    dropout_att: 0.1 # The dropout for multi-headed attention modules

    # set to non-zero to enable stochastic depth
    stochastic_depth_drop_prob: 0.0
    stochastic_depth_mode: linear  # linear or uniform
    stochastic_depth_start_layer: 1

  decoder:
    _target_: nemo.collections.asr.modules.ConvASRDecoder
    feat_in: null
    num_classes: -1
    vocabulary: []

  # config for InterCTC loss: https://arxiv.org/abs/2102.03216
  # specify loss weights and which layers to use for InterCTC
  # e.g., to reproduce the paper results, set loss_weights: [0.3]
  # and apply_at_layers: [8] (assuming 18 layers). Note that final
  # layer loss coefficient is automatically adjusted (to 0.7 in above example)
  interctc:
    loss_weights: []
    apply_at_layers: []

  optim:
    name: adamw
    lr: 1e-3
    # optimizer arguments
    betas: [0.9, 0.98]
    # less necessity for weight_decay as we already have large augmentations with SpecAug
    # you may need weight_decay for large models, stable AMP training, small datasets, or when lower augmentations are used
    # weight decay of 0.0 with lr of 2.0 also works fine
    weight_decay: 1e-3

    # scheduler setup
    sched:
      name: CosineAnnealing
      # Scheduler config override
      warmup_steps: 10000
      warmup_ratio: null
      min_lr: 1e-6
      max_steps: 1000000

trainer:
  devices: -1 # number of GPUs, -1 would use all available GPUs
  num_nodes: 1
  max_epochs: 1000
  max_steps: -1 # computed at runtime if not set
  val_check_interval: 1.0 # Set to 0.25 to check 4 times per epoch, or an int for number of iterations
  accelerator: auto
  strategy: ddp
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0
  precision: 32 # 16, 32, or bf16
  log_every_n_steps: 10  # Interval of logging.
  enable_progress_bar: True
  num_sanity_val_steps: 0 # number of steps to perform validation steps for sanity check the validation process before starting the training, setting to 0 disables it
  check_val_every_n_epoch: 1 # number of evaluations on validation every n epochs
  sync_batchnorm: true
  enable_checkpointing: False  # Provided by exp_manager
  logger: false  # Provided by exp_manager
  benchmark: false # needs to be false for models with variable-length speech input as it slows down training

exp_manager:
  exp_dir: output_dir
  name: ${name}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    # In case of multiple validation sets, first one is used
    monitor: "val_global_wer"
    mode: "min"
    save_top_k: 10
    always_save_nemo: True # Saves the checkpoints as nemo files instead of PTL checkpoints
  create_neptune_logger: False
  neptune_logger_kwargs:
      project: project
      name: experiment_name
      prefix: train
      log_model_checkpoints: false # Set to True if checkpoints need to be pushed to Neptune
      tags: tag # San specify as an array of strings in yaml array format
  # You need to set these two to True to continue the training
  resume_if_exists: True
  resume_ignore_no_checkpoint: True